## What is NumPy?

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.



## Why Use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

## Why is NumPy Faster Than Lists?

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

## Which Language is NumPy written in?

NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.



# Installation of NumPy

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

1.26.4


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr[4]

5

In [ ]:
arr0=np.array(23)
arr0

array(23)

In [ ]:
print(arr)

[1 2 3 4 5]


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
arr1 = np.array((1, 2, 3, 4, 5))

print(arr1)

[1 2 3 4 5]


In [ ]:
print(type(arr1))

<class 'numpy.ndarray'>


## Dimensions In Arrays

In [ ]:
a = np.array(42)  #0D array
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1.4, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
e=np.array([[[1],[2]],[[3],[4]],[[5],[6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

0
1
2
3
3


In [ ]:
print(a.ndim,"- D Array: \n",a)
print("____________________")
print(b.ndim,"- D Array: \n",b)
print("____________________")
print(c.ndim,"- D Array: \n",c)
print("____________________")
print(d.ndim,"- D Array: \n",d)
print("____________________")
print(e.ndim,"- D Array: \n",e)
print("____________________")

# print(e[2][1])

0 - D Array: 
 42
____________________
1 - D Array: 
 [1 2 3 4 5]
____________________
2 - D Array: 
 [[1.4 2.  3. ]
 [4.  5.  6. ]]
____________________
3 - D Array: 
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
____________________
3 - D Array: 
 [[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]
____________________


In [ ]:
print(c.ndim,"- D Array: \n",c)
print("Rows and Colums: ",c.shape)
print("Total Size: ",c.size)
print("Data Type of Array: ",c.dtype)


2 - D Array: 
 [[1.4 2.  3. ]
 [4.  5.  6. ]]
Rows and Colums:  (2, 3)
Total Size:  6
Data Type of Array:  float64


In [ ]:
a = np.array(1)

In [ ]:
a=np.array([1,2,3,4])

In [ ]:
import numpy as np

# New Lecture

Adding larger Dimensions

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=6)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[[1 2 3 4]]]]]]
number of dimensions : 6


In [ ]:
arr[0][0][0][0][0][3]
# traditional indexing

Operations on Array indexes

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [ ]:
arr=np.array([1,3,4,5,6,7])
even_sum=0
odd_sum=0
for i in range(len(arr)):
    if arr[i]%2==0:
        even_sum+=arr[i]
    else:
        odd_sum+=arr[i]
print("Even Values Sum:",even_sum)
print("Odd Values Sum:",odd_sum)



Even Values Sum: 10
Odd Values Sum: 16


Retriving Data

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr.shape)
print(arr[0][1]) #traditional indexing
print('2nd element on 1st row: ', arr[0, 1])

(2, 5)
2
2nd element on 1st row:  2


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1][0][0])
print("Access the first element of the first array of the second array:",arr[1, 0, 0])

7
Access the first element of the first array of the second array: 7


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


Slicing

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7,6,7])

print(arr[3:])

[4 5 6 7 6 7]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7,8])

print(arr[0:6:2])

[1 3 5]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


Type Casting
i,u,s,b

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
arr = np.array([1.9, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

# print(arr)
# print(arr.dtype)
# [1.9 2.1 3.1]
# float64

[1 2 3]
int32


In [ ]:
# Integer (i) with size 4 (32-bit integer)
int_array = np.array([1, 2, 3], dtype='i4')
print("Integer array (i4):", int_array, "| dtype:", int_array.dtype)

# Unsigned Integer (u) with size 2 (16-bit unsigned integer)
uint_array = np.array([1, 2, 3], dtype='u2')
print("Unsigned integer array (u2):", uint_array, "| dtype:", uint_array.dtype)

# Float (f) with size 8 (64-bit float)
float_array = np.array([1.1, 2.2, 3.3], dtype='f8')
print("Float array (f8):", float_array, "| dtype:", float_array.dtype)

# Byte string (S) with size 5 (fixed-length string of 5 bytes)
string_array = np.array([b'hello', b'worldq'], dtype='S5')
print("Byte string array (S5):", string_array, "| dtype:", string_array.dtype)

# Unicode string (U) with size 10 (fixed-length Unicode string of 10 characters)
unicode_array = np.array(['hello', 'world'], dtype='U10')
print("Unicode string array (U10):", unicode_array, "| dtype:", unicode_array.dtype)

Integer array (i4): [1 2 3] | dtype: int32
Unsigned integer array (u2): [1 2 3] | dtype: uint16
Float array (f8): [1.1 2.2 3.3] | dtype: float64
Byte string array (S5): [b'hello' b'world'] | dtype: |S5
Unicode string array (U10): ['hello' 'world'] | dtype: <U10


In [ ]:
# Unicode string array with a maximum length of 5 characters
unicode_array = np.array(['hello', 'world', '😊'], dtype='U1')
print(unicode_array)  # Output: ['hello' 'world' '😊']

# Note: Strings longer than 5 characters will be truncated
unicode_array = np.array(['Python', 'NumPy', '😊❤️'], dtype='U6')
print(unicode_array)  # Output: ['Pytho' 'NumPy' '😊❤️']

['h' 'w' '😊']
['Python' 'NumPy' '😊❤️']


In [ ]:
arr = np.array([1, 0, 3%2])

newarr = arr.astype(bool)
print(arr)
print(newarr)
print(newarr.dtype)

[1 0 1]
[ True False  True]
bool


In [ ]:
import numpy as np

# Lecture 3

## Copy and View Functions

Copy

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
arr[1]=34

print(arr)
print(x)

[42 34  3  4  5]
[1 2 3 4 5]


View

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
arr[1]=34

print(arr)
print(x)

[42 34  3  4  5]
[42 34  3  4  5]


Data Source Checking

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()
arr[2]=12

print(x.base)
print(y.base)

None
[ 1  2 12  4  5]


Shape

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


Reshape

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.shape)
newarr = arr.reshape(3, 4)
convert3d= arr.reshape(1,3,4)    #total size 12
print(convert3d)
print("____________________________")
print(newarr)

(12,)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
____________________________
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(1, 1, 12)

print(newarr)

[[[ 1  2  3  4  5  6  7  8  9 10 11 12]]]


Copy and View Case

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x=arr.reshape(2, 4)
print(x)
print("___________________")
print(x.base)

[[1 2 3 4]
 [5 6 7 8]]
___________________
[1 2 3 4 5 6 7 8]


Reshaping with unknown dimension

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(-1, 2, 4)

print(newarr)
flater=newarr.reshape(-1)
print("Flated Array:",flater)

[[[1 2 3 4]
  [5 6 7 8]]]
Flated Array: [1 2 3 4 5 6 7 8]


Flating Arrays

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


Convert the array into a 1D array

In [ ]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


Iterrating Arrays

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


Iterate on each scalar element of the 2-D array

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
        # print(type(x))
        # print(type(y))
        # print(y.ndim)
        print(y)

1
2
3
4
5
6


In [ ]:
arr=np.array([1,2,3,4])
for x in arr:
    print(x)

1
2
3
4


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# traditional way
for x in arr:
    # print(x)
    for y in x:
      # print(y)
      for z in y:
          print(z)

1
2
3
4
5
6
7
8
9
10
11
12


Iterating Arrays Using nditer()

In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


Iterating and Buffer

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer

op_dtypes

flags=['buffered']

In [53]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)
  print(x.dtype)
print(arr.dtype)


b'1'
|S21
b'2'
|S21
b'3'
|S21
int64


In [ ]:
arr.dtype

dtype('int32')

Iterating With Different Step Size

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::3]):           # 2 step slicing
  print(x)

1
4
5
8


Enumerated Iteration Using ndenumerate()

Enumeration means mentioning sequence number of somethings one by one.

ndenumerate()

In [ ]:
arr = np.array([[[1, 2, 3],[1,2,3],[1,2,3]]])
i=0
for idx, x in np.ndenumerate(arr):
    y=type(idx)
    y=idx
    z=type(x)
    a=y[0]
    b=y[1]
    c=y[2]

    # print(idx,"Index Type",y, "Type of X:",z)
    print("Index:",a,b,c,"Value", x)


Index: 0 0 0 Value 1
Index: 0 0 1 Value 2
Index: 0 0 2 Value 3
Index: 0 1 0 Value 1
Index: 0 1 1 Value 2
Index: 0 1 2 Value 3
Index: 0 2 0 Value 1
Index: 0 2 1 Value 2
Index: 0 2 2 Value 3


Enumerate on following 2D array's elements

In [ ]:
arr = np.array(([[1, 2, 3, 4], [5, 6, 7, 8]]) , ndmin =5)
# print(arr)
for idx, x in np.ndenumerate(arr):
  print("Index:",idx,"Values:", x)

Index: (0, 0, 0, 0, 0) Values: 1
Index: (0, 0, 0, 0, 1) Values: 2
Index: (0, 0, 0, 0, 2) Values: 3
Index: (0, 0, 0, 0, 3) Values: 4
Index: (0, 0, 0, 1, 0) Values: 5
Index: (0, 0, 0, 1, 1) Values: 6
Index: (0, 0, 0, 1, 2) Values: 7
Index: (0, 0, 0, 1, 3) Values: 8


In [ ]:
print(arr[0][0][0][0][0])

1


## Join two arrays

In [4]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr1,arr2)
print(arr)

[1 2 3] [4 5 6]
[1 2 3 4 5 6]


## Joining Arrays Using Stack Functions

In [13]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2),axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


## Stacking Along Rows

In [12]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


## Stacking Along Columns

In [15]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


## Stacking Along Height (depth)

In [17]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
arr3= np.array([7,8,9])
arr = np.dstack((arr1,arr2,arr3))

print(arr)

[[[1 4 7]
  [2 5 8]
  [3 6 9]]]


## Splitting NumPy Arrays

In [25]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(type(newarr))

<class 'list'>


Split the array in 4 parts


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

In [26]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [40]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[[1, 2, 3],
        [4, 5, 6]]]), array([[[ 7,  8,  9],
        [10, 11, 12]]]), array([], shape=(0, 2, 3), dtype=int64)]


In [41]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [43]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


## Search

In [50]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x[0][-1])

6


In [51]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x[0])

[1 3 5 7]


In [52]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x[0])

[0 2 4 6]


In [3]:
import numpy as np

## Sorting Arrays

In [5]:
arr = np.array([3, 2, 0, 1,4,0,1,2,4])

print(np.sort(arr))

[0 0 1 1 2 2 3 4 4]


### Albhabetical Sorting

In [7]:
arr = np.array(['banana','ball', 'cherry', 'apple','mubashir'])

print(np.sort(arr))


['apple' 'ball' 'banana' 'cherry' 'mubashir']


Boolean Sorting

In [9]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


2 D Array Sorting

In [13]:
arr = np.array([[3, 2, 4,4,6,2], [5, 0, 1,7,8,3]])

print(np.sort(arr))

[[2 2 3 4 4 6]
 [0 1 3 5 7 8]]


## Filtering Arrays

In [8]:
arr = np.array([41, 42, 43, 44,34])

x = [False, True, False, True,True]

newarr = arr[x]

print(newarr)

[42 44 34]


In [4]:
import numpy as np

Creating the Filter Array

In [48]:
arr = np.array([41, 42, 43, 44])

filter_arr = []

for element in arr:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [52]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = []

for element in arr:
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


Creating Filter Directly From Array

In [54]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [10]:
arr > 42

array([False, False,  True,  True, False])

In [57]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


## New Lecture 

#### Random 

In [16]:
from numpy import random as r

x = r.randint(100)

print(x)

69


In [20]:
x = r.rand()   # 0-1 

print(x)

0.8695690615458931


In [22]:
x=r.randint(100, size=(5))

print(x)

[42 47 23 67 80]


In [40]:
x = random.randint(10, size=(2,2))

print(x)

[[4 9]
 [4 9]]


In [46]:
x = random.rand(2,2)

print(x)

[[0.03430651 0.61127173]
 [0.68508221 0.01591973]]


In [30]:
x = random.rand(3, 5)

print(x)

[[0.45293752 0.09168521 0.79563949 0.79551905 0.21490401]
 [0.88345726 0.60851386 0.16492432 0.53350363 0.62628685]
 [0.80573506 0.91362386 0.40171027 0.08602657 0.77097346]]


In [72]:
x = random.choice([3, 5, 7, 9,12,32,43,23,12,33])

print(x)

43


In [70]:
x=random.randint(1)
user=int (input("Enter a Number Between 0 and 10:"))
if x==user:
    print("You Won")
else:
    print("You Loose")
    print("System Collected:",x)

Enter a Number Between 0 and 10: 1


You Loose
System Collected: 0


In [74]:
x = random.choice([0, 1], size=(3, 5))

print(x)

[[1 1 1 1 1]
 [1 1 1 1 0]
 [1 0 0 1 1]]


## Random Data Distribution

Probability Density Function: 
A function that describes a continuous probability. i.e. probability of all values in an array.

We can generate random numbers based on defined probabilities using the choice() method 
of the random module.

The choice() method allows us to specify the probability for each value.

In [82]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.4, 0.2], size=(100))

print(x)

[3 9 5 5 9 3 7 5 5 7 7 7 5 7 9 7 7 5 7 3 9 3 7 9 7 7 7 3 7 5 5 5 7 5 3 5 5
 5 5 5 7 3 5 7 3 7 3 7 7 3 9 7 3 9 7 7 5 7 3 3 5 7 5 7 3 9 7 7 7 7 7 3 7 5
 9 9 9 7 5 7 3 3 5 5 7 7 9 9 7 5 7 5 9 9 9 7 5 7 3 7]


In [86]:
count=0
count_3=0
count_5=0
count_7=0
count_9=0
for i in x:
    if ((i==5) |(i==3))|((i==7)|(i==9)):
        count+=1
    if i==3:
        count_3+=1
    if i==5:
        count_5+=1
    if i==7:
        count_7+=1
    if i==9:
        count_9+=1
        

print("Total Elements:",count)
print("Total Elements of 3:",count_3)
print("Total Elements of 5:",count_5)
print("Total Elements of 7:",count_7)
print("Total Elements of 9:",count_9)
total_count=count_3+count_5+count_7+count_9
print("Total Elements After:",total_count)

Total Elements: 100
Total Elements of 3: 18
Total Elements of 5: 26
Total Elements of 7: 40
Total Elements of 9: 16
Total Elements After: 100


In [88]:
p1=(count_3/total_count)*100
p2=(count_5/total_count)*100
p3=(count_7/total_count)*100
p4=(count_9/total_count)*100

In [90]:
print("P1:",p1)
print("P2:",p2)
print("P3:",p3)
print("P4:",p4)

P1: 18.0
P2: 26.0
P3: 40.0
P4: 16.0


In [94]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.1, 0.4, 0.4], size=(3, 5))

print(x)

[[3 7 7 5 7]
 [9 7 5 9 7]
 [9 9 7 5 9]]


In [1]:
import numpy as np

### New Lecture

### UFUNC 


universal functions

In [5]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


In [7]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


In [9]:
print(type(np.add))

<class 'numpy.ufunc'>


### UFUNC Arthematic functions

In [11]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


In [13]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
arr3 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2, arr3)

print(newarr)

[-10  -1   8  17  26  35]


In [15]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


In [81]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [83]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[      1000    3200000  729000000 -520093696       2500          0]


In [85]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [87]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [27]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)
qu=newarr[0]
rem= newarr[1]
print("Qutionents: ",qu,"\nRemenders: ",rem)

Qutionents:  [ 3  2  3  5 25  1] 
Remenders:  [ 1  6  3  0  0 27]


In [91]:
arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


### Truncate 

In [29]:
arr = np.trunc([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [37]:
arr = np.around(3.1622, 2)

print(arr)

3.16


In [39]:
arr = np.floor([-3.1666, 3.6667])

print(arr)

[-4.  3.]


In [41]:
arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


### UFUNC Summition

In [104]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)

[2 4 6]


In [49]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1,arr2])

print(newarr)

12


In [53]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


In [118]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=0)

print(newarr)

[2 4 6]


### Cumulative Sum

In [57]:
arr = np.array([1, 2, 3, 4, 5,4,6,7])

newarr = np.cumsum(arr)

print(newarr)

[ 1  3  6 10 15 19 25 32]


### UFUNC Product

In [59]:
arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)

24


In [65]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2], axis =0)

print(x)

[ 5 12 21 32]


In [67]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

[  24 1680]


In [69]:
arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)

print(newarr)

[   5   30  210 1680]


### NumPy LCM Lowest Common Multiple

In [71]:
num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

12


In [87]:
arr = np.array([3, 6])

x = np.lcm.reduce(arr)

print(x)

6


In [99]:
arr = np.arange(1, 11)

x = np.lcm.reduce(arr)
print(arr)
print(x)
# 2520/5

[ 1  2  3  4  5  6  7  8  9 10]
2520


### NumPy GCD Greatest Common Denominator or HCF

In [101]:
num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

3


In [103]:
arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)

4


### NumPy Trigonometric Functions

In [105]:
x = np.sin(np.pi/2)

print(x)

1.0


In [113]:
# np.pi/2
(22/7)/2

1.5714285714285714

In [115]:
np.sin(0.0)

0.0

In [117]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)

print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [129]:
sin_x=np.sin(0)
cos_x=np.cos(0)
tan_x=np.tan(0)

print(sin_x)
print(cos_x)
print(tan_x)

0.0
1.0
0.0


In [119]:
x = np.tan(0)

print(x)

0.0


In [222]:
arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [133]:
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


In [226]:
x = np.arcsin(1.0)

print(x)

1.5707963267948966


In [228]:
arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


In [135]:
base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

5.0


## END OF NUMPY