## What is NumPy?

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.



## Why Use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

## Why is NumPy Faster Than Lists?

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

## Which Language is NumPy written in?

NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.



# Installation of NumPy

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

1.26.4


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr[4]

5

In [ ]:
arr0=np.array(23)
arr0

array(23)

In [ ]:
print(arr)

[1 2 3 4 5]


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
arr1 = np.array((1, 2, 3, 4, 5))

print(arr1)

[1 2 3 4 5]


In [ ]:
print(type(arr1))

<class 'numpy.ndarray'>


## Dimensions In Arrays

In [ ]:
a = np.array(42)  #0D array
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1.4, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
e=np.array([[[1],[2]],[[3],[4]],[[5],[6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

0
1
2
3
3


In [ ]:
print(a.ndim,"- D Array: \n",a)
print("____________________")
print(b.ndim,"- D Array: \n",b)
print("____________________")
print(c.ndim,"- D Array: \n",c)
print("____________________")
print(d.ndim,"- D Array: \n",d)
print("____________________")
print(e.ndim,"- D Array: \n",e)
print("____________________")

# print(e[2][1])

0 - D Array: 
 42
____________________
1 - D Array: 
 [1 2 3 4 5]
____________________
2 - D Array: 
 [[1.4 2.  3. ]
 [4.  5.  6. ]]
____________________
3 - D Array: 
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
____________________
3 - D Array: 
 [[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]
____________________


In [ ]:
print(c.ndim,"- D Array: \n",c)
print("Rows and Colums: ",c.shape)
print("Total Size: ",c.size)
print("Data Type of Array: ",c.dtype)


2 - D Array: 
 [[1.4 2.  3. ]
 [4.  5.  6. ]]
Rows and Colums:  (2, 3)
Total Size:  6
Data Type of Array:  float64


In [ ]:
a = np.array(1)

In [ ]:
a=np.array([1,2,3,4])

In [ ]:
import numpy as np

# New Lecture

Adding larger Dimensions

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=6)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[[1 2 3 4]]]]]]
number of dimensions : 6


In [ ]:
arr[0][0][0][0][0][3]
# traditional indexing

Operations on Array indexes

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [ ]:
arr=np.array([1,3,4,5,6,7])
even_sum=0
odd_sum=0
for i in range(len(arr)):
    if arr[i]%2==0:
        even_sum+=arr[i]
    else:
        odd_sum+=arr[i]
print("Even Values Sum:",even_sum)
print("Odd Values Sum:",odd_sum)



Even Values Sum: 10
Odd Values Sum: 16


Retriving Data

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr.shape)
print(arr[0][1]) #traditional indexing
print('2nd element on 1st row: ', arr[0, 1])

(2, 5)
2
2nd element on 1st row:  2


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1][0][0])
print("Access the first element of the first array of the second array:",arr[1, 0, 0])

7
Access the first element of the first array of the second array: 7


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


Slicing

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7,6,7])

print(arr[3:])

[4 5 6 7 6 7]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7,8])

print(arr[0:6:2])

[1 3 5]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


Type Casting
i,u,s,b

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
arr = np.array([1.9, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

# print(arr)
# print(arr.dtype)
# [1.9 2.1 3.1]
# float64

[1 2 3]
int32


In [ ]:
# Integer (i) with size 4 (32-bit integer)
int_array = np.array([1, 2, 3], dtype='i4')
print("Integer array (i4):", int_array, "| dtype:", int_array.dtype)

# Unsigned Integer (u) with size 2 (16-bit unsigned integer)
uint_array = np.array([1, 2, 3], dtype='u2')
print("Unsigned integer array (u2):", uint_array, "| dtype:", uint_array.dtype)

# Float (f) with size 8 (64-bit float)
float_array = np.array([1.1, 2.2, 3.3], dtype='f8')
print("Float array (f8):", float_array, "| dtype:", float_array.dtype)

# Byte string (S) with size 5 (fixed-length string of 5 bytes)
string_array = np.array([b'hello', b'worldq'], dtype='S5')
print("Byte string array (S5):", string_array, "| dtype:", string_array.dtype)

# Unicode string (U) with size 10 (fixed-length Unicode string of 10 characters)
unicode_array = np.array(['hello', 'world'], dtype='U10')
print("Unicode string array (U10):", unicode_array, "| dtype:", unicode_array.dtype)

Integer array (i4): [1 2 3] | dtype: int32
Unsigned integer array (u2): [1 2 3] | dtype: uint16
Float array (f8): [1.1 2.2 3.3] | dtype: float64
Byte string array (S5): [b'hello' b'world'] | dtype: |S5
Unicode string array (U10): ['hello' 'world'] | dtype: <U10


In [ ]:
# Unicode string array with a maximum length of 5 characters
unicode_array = np.array(['hello', 'world', '😊'], dtype='U1')
print(unicode_array)  # Output: ['hello' 'world' '😊']

# Note: Strings longer than 5 characters will be truncated
unicode_array = np.array(['Python', 'NumPy', '😊❤️'], dtype='U6')
print(unicode_array)  # Output: ['Pytho' 'NumPy' '😊❤️']

['h' 'w' '😊']
['Python' 'NumPy' '😊❤️']


In [ ]:
arr = np.array([1, 0, 3%2])

newarr = arr.astype(bool)
print(arr)
print(newarr)
print(newarr.dtype)

[1 0 1]
[ True False  True]
bool


In [ ]:
import numpy as np

# Lecture 3

## Copy and View Functions

Copy

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
arr[1]=34

print(arr)
print(x)

[42 34  3  4  5]
[1 2 3 4 5]


View

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
arr[1]=34

print(arr)
print(x)

[42 34  3  4  5]
[42 34  3  4  5]


Data Source Checking

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()
arr[2]=12

print(x.base)
print(y.base)

None
[ 1  2 12  4  5]


Shape

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


Reshape

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.shape)
newarr = arr.reshape(3, 4)
convert3d= arr.reshape(1,3,4)    #total size 12
print(convert3d)
print("____________________________")
print(newarr)

(12,)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
____________________________
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(1, 1, 12)

print(newarr)

[[[ 1  2  3  4  5  6  7  8  9 10 11 12]]]


Copy and View Case

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x=arr.reshape(2, 4)
print(x)
print("___________________")
print(x.base)

[[1 2 3 4]
 [5 6 7 8]]
___________________
[1 2 3 4 5 6 7 8]


Reshaping with unknown dimension

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(-1, 2, 4)

print(newarr)
flater=newarr.reshape(-1)
print("Flated Array:",flater)

[[[1 2 3 4]
  [5 6 7 8]]]
Flated Array: [1 2 3 4 5 6 7 8]


Flating Arrays

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


Convert the array into a 1D array

In [ ]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


Iterrating Arrays

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


Iterate on each scalar element of the 2-D array

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
        # print(type(x))
        # print(type(y))
        # print(y.ndim)
        print(y)

1
2
3
4
5
6


In [ ]:
arr=np.array([1,2,3,4])
for x in arr:
    print(x)

1
2
3
4


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# traditional way
for x in arr:
    # print(x)
    for y in x:
      # print(y)
      for z in y:
          print(z)

1
2
3
4
5
6
7
8
9
10
11
12


Iterating Arrays Using nditer()

In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


Iterating and Buffer

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer

op_dtypes

flags=['buffered']

In [53]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)
  print(x.dtype)
print(arr.dtype)


b'1'
|S21
b'2'
|S21
b'3'
|S21
int64


In [ ]:
arr.dtype

dtype('int32')

Iterating With Different Step Size

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::3]):           # 2 step slicing
  print(x)

1
4
5
8


Enumerated Iteration Using ndenumerate()

Enumeration means mentioning sequence number of somethings one by one.

ndenumerate()

In [ ]:
arr = np.array([[[1, 2, 3],[1,2,3],[1,2,3]]])
i=0
for idx, x in np.ndenumerate(arr):
    y=type(idx)
    y=idx
    z=type(x)
    a=y[0]
    b=y[1]
    c=y[2]

    # print(idx,"Index Type",y, "Type of X:",z)
    print("Index:",a,b,c,"Value", x)


Index: 0 0 0 Value 1
Index: 0 0 1 Value 2
Index: 0 0 2 Value 3
Index: 0 1 0 Value 1
Index: 0 1 1 Value 2
Index: 0 1 2 Value 3
Index: 0 2 0 Value 1
Index: 0 2 1 Value 2
Index: 0 2 2 Value 3


Enumerate on following 2D array's elements

In [ ]:
arr = np.array(([[1, 2, 3, 4], [5, 6, 7, 8]]) , ndmin =5)
# print(arr)
for idx, x in np.ndenumerate(arr):
  print("Index:",idx,"Values:", x)

Index: (0, 0, 0, 0, 0) Values: 1
Index: (0, 0, 0, 0, 1) Values: 2
Index: (0, 0, 0, 0, 2) Values: 3
Index: (0, 0, 0, 0, 3) Values: 4
Index: (0, 0, 0, 1, 0) Values: 5
Index: (0, 0, 0, 1, 1) Values: 6
Index: (0, 0, 0, 1, 2) Values: 7
Index: (0, 0, 0, 1, 3) Values: 8


In [ ]:
print(arr[0][0][0][0][0])

1


## Join two arrays

In [4]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr1,arr2)
print(arr)

[1 2 3] [4 5 6]
[1 2 3 4 5 6]


## Joining Arrays Using Stack Functions

In [13]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2),axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


## Stacking Along Rows

In [12]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


## Stacking Along Columns

In [15]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


## Stacking Along Height (depth)

In [17]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
arr3= np.array([7,8,9])
arr = np.dstack((arr1,arr2,arr3))

print(arr)

[[[1 4 7]
  [2 5 8]
  [3 6 9]]]


## Splitting NumPy Arrays

In [25]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(type(newarr))

<class 'list'>


Split the array in 4 parts


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

In [26]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [40]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[[1, 2, 3],
        [4, 5, 6]]]), array([[[ 7,  8,  9],
        [10, 11, 12]]]), array([], shape=(0, 2, 3), dtype=int64)]


In [41]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [43]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


## Search

In [50]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x[0][-1])

6


In [51]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x[0])

[1 3 5 7]


In [52]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x[0])

[0 2 4 6]
